In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style
import matplotlib as mpl
import autograd
from task3module.task3module import *
mpl.style.use('classic')
plt.figure(figsize=(8, 6), dpi = 80)

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [2]:
%matplotlib inline

In [3]:
np.random.seed(43)

In [4]:
N = 101
x = np.linspace(0, 1, N)
alpha = 0.785
beta = 0.31
y = alpha*x + beta + np.random.normal(size = N)

In [5]:
def cost_function(a, b):
    y_pred = a*x+b
    return squares(y_pred, y)

def cost_function_v(theta):
    return cost_function(theta[0], theta[1])

def cost_function_grad(theta):
    df1 = 2*np.sum(x*(theta[0]*x+theta[1]-y))
    df2 = 2*np.sum(theta[0]*x+theta[1]-y)
    return np.array([df1, df2], dtype=float)

def cost_function_hess(theta):
    df11 = 2*np.sum(np.square(x))
    df12 = 2*np.sum(x)
    df22 = 2*x.shape[0]
    return np.array([[df11, df12], [df12, df22]], dtype=float)


In [6]:
limits = np.array([[0, 1], [0, 1]], dtype=float)

In [7]:
newtons(cost_function_v, limits, np.array([0.1, 0.1]), funcgrad=cost_function_grad,
        funchess=cost_function_hess, optpoint = np.array([alpha, beta]))

(array([0.68456203, 0.42617877]),
 92.14858746546793,
 {'iterations': 2,
  'funccalcs': 0,
  'gradcalcs': 2,
  'hesscalcs': 2,
  'matrixinversions': 2},
 0.15357504216757092)

In [10]:
levenmarq(cost_function_v, limits, np.array([0.1, 0.1]), funcgrad=cost_function_grad,
          funchess=cost_function_hess, regulpar=1., optpoint = np.array([alpha, beta]))


(array([0.68455491, 0.42618259]),
 92.14858746590969,
 {'iterations': 4,
  'funccalcs': 0,
  'gradcalcs': 4,
  'hesscalcs': 4,
  'matrixinversions': 4},
 0.15358258467357028)

In [11]:
levenmarq(cost_function_v, limits, np.array([0.1, 0.1]), funcgrad=cost_function_grad,
          funchess=cost_function_hess, regulpar=(0., 10.), optpoint = np.array([alpha, beta]))

(array([0.68456203, 0.42617877]),
 92.14858746546791,
 {'iterations': 2,
  'funccalcs': 46,
  'gradcalcs': 2,
  'hesscalcs': 2,
  'matrixinversions': 42},
 0.1535750423681571)